#!/usr/bin/env python 
# -*- coding: utf-8 -*-
# @Time    : 2019/12/5 15:46
# @Author  : jwliu
# @Site    : 
# @Software: PyCharm
import pickle
import numpy
import os
import pandas as pd
from settlement.fee.fee import Fee


class Fee_ghls(Fee):
    def __init__(self):
        Fee.__init__(self)
        self.OpenFeeRate_dict = pd.Series({"stock":0.0014,
            "ZC": 0.000001,
                            "JM": 0.000181,
                            "J": 0.000181,
                            "I": 0.000061,
                            "RB": 0.000101,
                            "HC": 0.000101,
                            "FG": 0.000001,
                            "SF": 0.000001,
                            "SM": 0.000001,
                            "TA": 0.000001,
                            "BU": 0.000101,
                            "EG": 0.000001,
                            "RU": 0.000046,
                            "MA": 0.000001,
                            "PP": 0.000031,
                            "V": 0.000001,
                            "L": 0.000001,
                            "SP": 0.000051,
                            "FU": 0.000051,
                            "SC": 0.000001,
                            "A": 0.000001,
                            "B": 0.000001,
                            "C": 0.000001,
                            "Y": 0.000001,
                            "CS": 0.000001,
                            "JD": 0.000151,
                            "CF": 0.000001,
                            "M": 0.000001,
                            "P": 0.000001,
                            "RM": 0.000001,
                            "OI": 0.000001,
                            "SR": 0.000001,
                            "AP": 0.000001,
                            "CJ": 0.000001,
                            "AG": 0.000051,
                            "AU": 0.000001,
                            "CU": 0.000051,
                            "AL": 0.000001,
                            "NI": 0.000001,
                            "ZN": 0.000001,
                            "PB": 0.000041,
                            "SN": 0.000001,
                            "IF": 0.000038,
                            "IH": 0.000038,
                            "IC": 0.000038,
            "TS": 0,
            "TF": 0,
            "T": 0
                            })
        self.OpenFee_dict = pd.Series({"stock":0,
            "ZC": 4,
            "JM": 0,
            "J": 0,
            "I": 0,
            "RB": 0,
            "HC": 0,
            "FG": 3,
            "SF": 3,
            "SM": 3,
            "TA": 3,
            "BU": 0,
            "EG": 4,
            "RU": 0,
            "MA": 2,
            "PP": 0,
            "V": 2,
            "L": 2,
            "SP": 0,
            "FU": 0,
            "SC": 20,
            "A": 2,
            "B": 2,
            "C": 1.2,
            "Y": 2.5,
            "CS": 1.5,
            "JD": 0,
            "CF": 4.3,
            "M": 1.5,
            "P": 2.5,
            "RM": 1.5,
            "OI": 2,
            "SR": 3,
            "AP": 5,
            "CJ": 3,
            "AG": 0,
            "AU": 10,
            "CU": 0,
            "AL": 3,
            "NI": 6,
            "ZN": 3,
            "PB": 0,
            "SN": 3,
            "TS": 3,
            "TF": 3,
            "T": 3
        })

        self.CloseFeeRate_dict = pd.Series({"stock":0.00013,"ZC": 0.000001,
                             "JM": 0.000061,
                             "J": 0.000061,
                             "I": 0.000061,
                             "RB": 0.000101,
                             "HC": 0.000101,
                             "FG": 0.000001,
                             "SF": 0.000001,
                             "SM": 0.000001,
                             "TA": 0.000001,
                             "BU": 0.000101,
                             "EG": 0.000001,
                             "RU": 0.000046,
                             "MA": 0.000001,
                             "PP": 0.000061,
                             "V": 0.000001,
                             "L": 0.000001,
                             "SP": 0.000051,
                             "FU": 0.000051,
                             "SC": 0.000001,
                             "A": 0.000001,
                             "B": 0.000001,
                             "C": 0.000001,
                             "Y": 0.000001,
                             "CS": 0.000001,
                             "JD": 0.000151,
                             "CF": 0.000001,
                             "M": 0.000001,
                             "P": 0.000001,
                             "RM": 0.000001,
                             "OI": 0.000001,
                             "SR": 0.000001,
                             "AP": 0.000001,
                             "CJ": 0.000001,
                             "AG": 0.000051,
                             "AU": 0.000001,
                             "CU": 0.000051,
                             "AL": 0.000001,
                             "NI": 0.000001,
                             "ZN": 0.000001,
                             "PB": 0.000041,
                             "SN": 0.000001,
                             "IF": 0.000038,
                             "IH": 0.000038,
                             "IC": 0.000038,
            "TS": 0,
            "TF": 0,
            "T": 0})
        self.CloseFee_dict = pd.Series({"stock":0,
            "ZC": 4,
            "JM": 0,
            "J": 0,
            "I": 0,
            "RB": 0,
            "HC": 0,
            "FG": 3,
            "SF": 3,
            "SM": 3,
            "TA": 3,
            "BU": 0,
            "EG": 4,
            "RU": 0,
            "MA": 2,
            "PP": 0,
            "V": 2,
            "L": 2,
            "SP": 0,
            "FU": 0,
            "SC": 20,
            "A": 2,
            "B": 2,
            "C": 1.2,
            "Y": 2.5,
            "CS": 1.5,
            "JD": 0,
            "CF": 4.3,
            "M": 1.5,
            "P": 2.5,
            "RM": 1.5,
            "OI": 2,
            "SR": 3,
            "AP": 5,
            "CJ": 3,
            "AG": 0,
            "AU": 10,
            "CU": 0,
            "AL": 3,
            "NI": 6,
            "ZN": 3,
            "PB": 0,
            "SN": 3,
            "TS": 0,
            "TF": 0,
            "T": 0
        })

        self._fee_df = pd.concat([self.OpenFeeRate_dict,self.OpenFee_dict,self.CloseFeeRate_dict,self.CloseFee_dict],axis=1)
        self._fee_df.columns = ['OpenFeeRate','OpenFee','CloseFeeRate','CloseFee']
        self._fee_df.fillna(0.0001,inplace=True)
    def calc_fee_ex(self, transaction_df):
        transaction_df = pd.merge(transaction_df,self._fee_df,how='left',right_index=True,left_on='product_id',suffixes=('_info',''))
        fee = numpy.abs(transaction_df['transactions'] * transaction_df['transaction_price'] * transaction_df['contract_size'])  * transaction_df['OpenFeeRate'] +  numpy.abs(transaction_df['transactions']) * transaction_df['OpenFee']
        return fee

    def calc_fee(self, product_id, volumn, price, contract_size, is_open=True):
        product_id = product_id.upper()
        if is_open:
            fee_rate = self.OpenFeeRate_dict[product_id] if product_id in self.OpenFeeRate_dict else 0.0001
            fee = self.OpenFee_dict[product_id] if product_id in self.OpenFee_dict else 0
            return abs(volumn * price * contract_size) * fee_rate + abs(volumn) * fee
        else:
            fee_rate = self.CloseFeeRate_dict[product_id] if product_id in self.CloseFeeRate_dict else 0.0001
            fee = self.CloseFee_dict[product_id] if product_id in self.CloseFee_dict else 0
            return abs(volumn * price * contract_size) * fee_rate + abs(volumn) * fee
